// Complete promotions seeding data
export const createAllPromotions = async (createPromotion: any, brands: any) => {
  // Gamesa Promotions
  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Una probada de Europa",
    slug: "una-probada-de-europa",
    description: "En 2002, Vualá introdujo una línea de croissants inspirados en la repostería europea con rellenos de chocolate, vainilla y fresa. Esta campaña ofrecía postales de Europa.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: "https://www.youtube.com/watch?v=qsq1w3eZX2E",
    buffetGamesVideoUrl: null,
    startYear: 2002,
    endYear: 2002,
    category: "Tazos",
    tags: ["postales"],
    sortOrder: 0,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Tattoomania",
    slug: "tattoomania-2003",
    description: "Promoción de Gamesa con tatuajes temporales, pulseras y colgantes con diseños vanguardistas desarrollada por Faustinbros.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: "https://www.youtube.com/watch?v=qsq1w3eZX2E",
    buffetGamesVideoUrl: null,
    startYear: 2003,
    endYear: 2003,
    category: "Tazos",
    tags: ["tattoo-mania", "faustin0bros", "tatuajes", "pulseras", "colgantes"],
    sortOrder: 1,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Askistix",
    slug: "askistix-2004",
    description: "Promoción de Gamesa con 20 calcomanías diferentes con personajes de temática humorística y grotesca, inspirados en las Garbage Pail Kids.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Askistix 2004 chocolate frontal_1755196507567_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/Askistix 2004 chocolate frontal_1755196507567_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2004,
    endYear: 2004,
    category: "Stickers",
    tags: ["askistix", "calcomanias", "stickers"],
    sortOrder: 2,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Tattoomania la Colección alternativa",
    slug: "tattoomania-alternativa-2004",
    description: "Segunda versión de la popular promoción Tattoomania con nuevos diseños y colecciones alternativas.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2004,
    endYear: 2004,
    category: "Tazos",
    tags: ["tattoomania", "alternativa"],
    sortOrder: 3,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "The Dog 2004",
    slug: "the-dog-2004",
    description: "Promoción kawaii con lindos perritos de diferentes razas. Colecciona todos los cachorros de The Dog.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/The dog 2004 vainilla frontal_1755219753444_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/The dog 2004 vainilla frontal_1755219753444_rotated.png"],
    wrapperRotation: 90,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2004,
    endYear: 2004,
    category: "Mini colgantes",
    tags: ["the-dog", "kawaii", "perritos", "razas"],
    sortOrder: 4,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Conexion Alien",
    slug: "conexion-alien-2004",
    description: "Promoción futurista con temática alienígena y de ciencia ficción con stickers y mini colgantes.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Chocolate conexion alien 2004 frontal_1755196507572_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/Chocolate conexion alien 2004 frontal_1755196507572_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2004,
    endYear: 2004,
    category: "Stickers, Mini Colgantes",
    tags: ["alien", "ciencia-ficcion"],
    sortOrder: 5,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Corazones de Gamesa",
    slug: "corazones-gamesa-2005",
    description: "Promoción romántica con diseños de corazones y temática del amor.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2005,
    endYear: 2005,
    category: "Tazos",
    tags: ["corazones", "amor"],
    sortOrder: 6,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Bob Esponja",
    slug: "bob-esponja-2005",
    description: "Primera promoción de Bob Esponja con tazos coleccionables del personaje favorito de Nickelodeon.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2005,
    endYear: 2005,
    category: "Tazos",
    tags: ["bob-esponja", "nickelodeon"],
    sortOrder: 7,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "The Dog y the Cat",
    slug: "the-dog-the-cat-2007",
    description: "En octubre de 2007, Vualá volvió al fenómeno de los perritos con la primera licencia en repetir, incluyendo Laser Stix y mascotas miniatura.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2007,
    endYear: 2007,
    category: "Tazos",
    tags: ["the-dog", "the-cat", "laser-stix"],
    sortOrder: 8,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Funki Punky Peores que nunca",
    slug: "funki-punky-peores-2007",
    description: "Promoción de la serie Funki Punky con personajes rebeldes y diseños alternativos.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2007,
    endYear: 2007,
    category: "Tazos",
    tags: ["funki-punky", "rebeldes"],
    sortOrder: 9,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Funki Punky by Faustin Bros",
    slug: "funki-punky-faustin-2007",
    description: "Colaboración especial entre Gamesa y Faustin Bros para la línea Funki Punky.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2007,
    endYear: 2007,
    category: "Tazos",
    tags: ["funki-punky", "faustin-bros"],
    sortOrder: 10,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Reyes de las Olas",
    slug: "reyes-de-las-olas-vuala-2007",
    description: "Promoción temática de surf y deportes acuáticos con los reyes de las olas.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Chocolate frontalreyes de las olas_1755196507573_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/Chocolate frontalreyes de las olas_1755196507573_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2007,
    endYear: 2007,
    category: "Tazos",
    tags: ["surf", "deportes-acuaticos"],
    sortOrder: 11,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.sabritas.id,
    name: "Spiderman 3",
    slug: "spiderman-3-vuala-2007",
    description: "Promoción épica de Spider-Man 3 con stickers, tatoos, mini colgantes y pegajosos del hombre araña.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Vainilla  frontal spiderman 3_1755219753445_rotated.png",
    wrapperPhotosUrls: [
      "/attached_assets/rotated/Vainilla  frontal spiderman 3_1755219753445_rotated.png",
      "/attached_assets/rotated/Chocolate frontal spiderman 3_1755196507572_rotated.png"
    ],
    wrapperRotation: 90,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2007,
    endYear: 2007,
    category: "Stickers, Tatoos, Mini Colgantes, Pegajosos",
    tags: ["spiderman", "marvel", "superheros"],
    sortOrder: 12,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Fonomania 2.0",
    slug: "fonomania-vuala-2008",
    description: "Promoción musical con temática de la música y fonógrafos modernos.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Fonomania 2008 frontal chocolate_1755219298611_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/Fonomania 2008 frontal chocolate_1755219298611_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2008,
    endYear: 2008,
    category: "Tazos",
    tags: ["musica", "fonomania"],
    sortOrder: 13,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Dance Mania 2008",
    slug: "dance-mania-2008",
    description: "Promoción de baile y música con tatoos de temática de danza y movimiento.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Dance mania 2008 vainilla frontal_1755196507566_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/Dance mania 2008 vainilla frontal_1755196507566_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2008,
    endYear: 2008,
    category: "Tatoos",
    tags: ["baile", "musica", "danza"],
    sortOrder: 14,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.gamesa.id,
    name: "Ecoloquitos 2009",
    slug: "ecoloquitos-2009",
    description: "Promoción ecológica con personajes que promueven el cuidado del medio ambiente.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Cajeta frontal ecolokitos_1755196507570_rotated.png",
    wrapperPhotosUrls: [
      "/attached_assets/rotated/Cajeta frontal ecolokitos_1755196507570_rotated.png",
      "/attached_assets/rotated/Chocolate frontal ecolokitos_1755196507572_rotated.png"
    ],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2008,
    endYear: 2009,
    category: "Tazos",
    tags: ["ecologia", "medio-ambiente"],
    sortOrder: 15,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  // Vualá Promotions
  await createPromotion({
    brandId: brands.vuala.id,
    name: "Bob Esponja en Movimiento",
    slug: "bob-esponja-movimiento-2009",
    description: "Promoción de Bob Esponja con tazos que muestran al personaje en diferentes movimientos y poses.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/bob espona en movimiento 2009 frontal cajeta_1755196507568_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/bob espona en movimiento 2009 frontal cajeta_1755196507568_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2009,
    endYear: 2009,
    category: "Tazos",
    tags: ["bob-esponja", "movimiento", "nickelodeon"],
    sortOrder: 16,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Looney Tunes 2009",
    slug: "looney-tunes-2009",
    description: "La primera promoción de Vualá en estrenar el nuevo logo moderno que conocemos hoy. Esta colección poco recordada marcó la despedida del icónico logo azul que caracterizó una generación entera. Los Looney Tunes llegaron en forma de lanza discos con stickers de los personajes clásicos de Warner Bros. La colección se dividió en tres categorías: Ultra Disk de colores vibrantes, Xtreme Disk dorados de edición especial, e Iron Disk plateados de alta resistencia. Cada envoltura incluía reglas impresas para que los niños pudieran jugar y competir con sus discos. Esta promoción representa un momento histórico en la evolución de la marca Vualá.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2009,
    endYear: 2009,
    category: "Lanza Discos",
    tags: ["looney-tunes", "warner-bros", "bugs-bunny", "lanza-discos", "logo-moderno"],
    sortOrder: 17,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "CMLL Vualá",
    slug: "cmll-vuala-2009",
    description: "Promoción de lucha libre en colaboración con el Consejo Mundial de Lucha Libre con spinners.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2009,
    endYear: 2009,
    category: "Spinners",
    tags: ["lucha-libre", "cmll", "deportes"],
    sortOrder: 18,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Vive el futbol con huevos",
    slug: "vive-futbol-huevos-2010",
    description: "Promoción futbolística basada en la película de animación mexicana con humor y deportes.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Vive el futbol con huevos 2010 frontal chocolate_1755219753446_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/Vive el futbol con huevos 2010 frontal chocolate_1755219753446_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2010,
    endYear: 2010,
    category: "Tazos",
    tags: ["futbol", "huevos", "deportes", "animacion"],
    sortOrder: 19,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "El Chavo Animado",
    slug: "el-chavo-sorpresa",
    description: "Promoción de El Chavo del Ocho en su versión animada con figuras sorpresa coleccionables.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2010,
    endYear: 2010,
    category: "Figuras",
    tags: ["el-chavo", "chespirito", "animado"],
    sortOrder: 20,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Funky Rebeldes con causa",
    slug: "funky-rebeldes-causa-2010",
    description: "Promoción de la serie Funky con personajes rebeldes que luchan por causas justas.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2010,
    endYear: 2010,
    category: "Tazos",
    tags: ["funky", "rebeldes", "causa"],
    sortOrder: 21,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "The Dog 2010",
    slug: "the-dog-vuala-2010",
    description: "Nueva edición de la popular serie The Dog con nuevas razas y poses de perritos kawaii.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2010,
    endYear: 2010,
    category: "Tazos",
    tags: ["the-dog", "perritos", "kawaii"],
    sortOrder: 22,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Funki Punky Extremo",
    slug: "funki-punky-extremo-vuala-2011",
    description: "Versión extrema de los Funki Punky con diseños más atrevidos y personajes únicos.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Cajeta funki punky extremo_1755196507570_rotated.png",
    wrapperPhotosUrls: [
      "/attached_assets/rotated/Cajeta funki punky extremo_1755196507570_rotated.png",
      "/attached_assets/rotated/vainilla funki punky extremo_1755219753446_rotated.png"
    ],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2011,
    endYear: 2011,
    category: "Tazos",
    tags: ["funki-punky", "extremo", "alternativo"],
    sortOrder: 23,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Aliens Eco-Invasores",
    slug: "aliens-eco-invasores-2011",
    description: "Promoción de aliens que invaden la Tierra para enseñar sobre ecología y cuidado ambiental.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2011,
    endYear: 2011,
    category: "Tazos",
    tags: ["aliens", "ecologia", "invasion"],
    sortOrder: 24,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "The Dog 2011",
    slug: "the-dog-2011",
    description: "Edición 2011 de The Dog con nuevas fotografías de cachorros adorables.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2011,
    endYear: 2011,
    category: "Tazos",
    tags: ["the-dog", "cachorros", "fotografía"],
    sortOrder: 25,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Muévete con huevo cartoon",
    slug: "muevete-huevo-cartoon-2011",
    description: "Promoción basada en la película de animación mexicana con personajes en movimiento.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2011,
    endYear: 2011,
    category: "Tazos",
    tags: ["huevos", "cartoon", "animacion", "mexicana"],
    sortOrder: 26,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Bob Esponja 2012 Pega y Deco",
    slug: "bob-esponja-pega-deco-2012",
    description: "Promoción de Bob Esponja con tazos que se pueden pegar y decorar en diferentes superficies.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Bob esponja 2012 Cajeta frontal_1755196507568_rotated.png",
    wrapperPhotosUrls: [
      "/attached_assets/rotated/Bob esponja 2012 Cajeta frontal_1755196507568_rotated.png",
      "/attached_assets/rotated/Bob esponja 2012 vainilla frontal_1755196507569_rotated.png"
    ],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2012,
    endYear: 2012,
    category: "Tazos",
    tags: ["bob-esponja", "pega", "decoracion"],
    sortOrder: 27,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "El Chavo Plateado y Dorado",
    slug: "el-chavo-plateado-dorado-2012",
    description: "Edición especial de El Chavo con tazos plateados y dorados de colección limitada.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2012,
    endYear: 2012,
    category: "Tazos",
    tags: ["el-chavo", "plateado", "dorado", "coleccion"],
    sortOrder: 28,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Los Simpson Olímpicos",
    slug: "los-simpson-olimpicos-2012",
    description: "Promoción de Los Simpson temática de los Juegos Olímpicos con deportes y competencias.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2012,
    endYear: 2012,
    category: "Tazos",
    tags: ["los-simpson", "olimpicos", "deportes"],
    sortOrder: 29,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Angry Birds Space",
    slug: "angry-birds-space-vuala-2012",
    description: "Promoción de Angry Birds Space con los pájaros enojados en aventuras espaciales.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2012,
    endYear: 2012,
    category: "Tazos",
    tags: ["angry-birds", "space", "espacio"],
    sortOrder: 30,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "La Era del Hielo 4",
    slug: "la-era-del-hielo-2012",
    description: "Promoción de la cuarta película de La Era del Hielo con figuras de los personajes principales.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2012,
    endYear: 2012,
    category: "Figuras",
    tags: ["era-del-hielo", "pelicula", "animacion"],
    sortOrder: 31,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "El Show de los Looney Tunes",
    slug: "show-looney-tunes-vuala-2013",
    description: "Promoción del show clásico de los Looney Tunes con Bugs Bunny, Pato Lucas y más.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2013,
    endYear: 2013,
    category: "Tazos",
    tags: ["looney-tunes", "bugs-bunny", "clasicos"],
    sortOrder: 32,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Super Funki Punky",
    slug: "super-funki-punky-vuala-2013",
    description: "Versión súper de los Funki Punky con poderes especiales y diseños únicos.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2013,
    endYear: 2013,
    category: "Tazos",
    tags: ["funki-punky", "super", "poderes"],
    sortOrder: 33,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Pingüinos de Madagascar",
    slug: "pinguinos-madagascar-vuala-2014",
    description: "Promoción de los pingüinos espías de Madagascar en aventuras de acción y comedia.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2014,
    endYear: 2014,
    category: "Tazos",
    tags: ["pinguinos", "madagascar", "espias"],
    sortOrder: 34,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Angry Birds Go",
    slug: "angry-birds-go",
    description: "Emocionante promoción de Vualá con personajes de Angry Birds Go. Colecciona todos los pájaros y cerditos en carreras.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/vainilla angry birds GO_1755219753445_rotated.png",
    wrapperPhotosUrls: [
      "/attached_assets/rotated/vainilla angry birds GO_1755219753445_rotated.png",
      "/attached_assets/rotated/Cajeta angry birds Go_1755196507570_rotated.png",
      "/attached_assets/rotated/Chocolate angry birds Go_1755196507571_rotated.png"
    ],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2014,
    endYear: 2014,
    category: "figuras",
    tags: ["angry-birds", "videojuegos", "figuras", "coleccionables"],
    sortOrder: 35,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Las Tortugas Ninja",
    slug: "tortugas-ninja-vuala-2014",
    description: "Promoción de las Tortugas Ninja con Leonardo, Donatello, Miguel Ángel y Rafael en acción.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Cajeta tortugas ninja_1755196507571_rotated.png",
    wrapperPhotosUrls: [
      "/attached_assets/rotated/Cajeta tortugas ninja_1755196507571_rotated.png",
      "/attached_assets/rotated/vainilla tortugas ninja_1755219753446_rotated.png"
    ],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2014,
    endYear: 2014,
    category: "Tazos",
    tags: ["tortugas-ninja", "heroes", "accion"],
    sortOrder: 36,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Hora de Aventura",
    slug: "hora-aventura-vuala-2014",
    description: "Promoción de Adventure Time con Finn y Jake en aventuras matemáticas.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2014,
    endYear: 2014,
    category: "Tazos",
    tags: ["adventure-time", "finn", "jake", "cartoon-network"],
    sortOrder: 37,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Minions",
    slug: "minions-2015",
    description: "Promoción de los Minions con las criaturas amarillas más divertidas del cine.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/minions chocolate_1755219753443_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/minions chocolate_1755219753443_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2015,
    endYear: 2015,
    category: "Figuras",
    tags: ["minions", "despicable-me", "amarillo"],
    sortOrder: 38,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "El Chavo Mini",
    slug: "el-chavo-mini-2015",
    description: "Versión mini de El Chavo del Ocho con figuras pequeñas y coleccionables.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/El chavo mini 2015 vainilla_1755219298610_rotated.png",
    wrapperPhotosUrls: [
      "/attached_assets/rotated/El chavo mini 2015 vainilla_1755219298610_rotated.png",
      "/attached_assets/rotated/El chavo mini chocolate_1755219298610_rotated.png"
    ],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2015,
    endYear: 2015,
    category: "Figuras",
    tags: ["el-chavo", "mini", "chespirito"],
    sortOrder: 39,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Avengers Era de Ultrón",
    slug: "avengers-era-de-ultron",
    description: "Promoción de los Vengadores en la Era de Ultrón con Iron Man, Capitán América y más héroes.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Avengers cajeta_1755196507567_rotated.png",
    wrapperPhotosUrls: [
      "/attached_assets/rotated/Avengers cajeta_1755196507567_rotated.png",
      "/attached_assets/rotated/Avengers vainilla_1755196507568_rotated.png"
    ],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2015,
    endYear: 2015,
    category: "Figuras",
    tags: ["avengers", "marvel", "ultron", "superheros"],
    sortOrder: 40,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  // Modern Vualá Promotions (2017-2025)
  await createPromotion({
    brandId: brands.vuala.id,
    name: "Bob Esponja 2017",
    slug: "bob-esponja-2017",
    description: "Nueva edición de Bob Esponja con figuras modernas del personaje de Nickelodeon.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2017,
    endYear: 2017,
    category: "Figuras",
    tags: ["bob-esponja", "nickelodeon", "2017"],
    sortOrder: 41,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Hora de Aventura 2018",
    slug: "hora-de-aventura-2018",
    description: "Segunda edición de Adventure Time con Finn, Jake y nuevos personajes de la Tierra de Ooo.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Frontal chocolate hora de aventura 2018_1755219298611_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/Frontal chocolate hora de aventura 2018_1755219298611_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2018,
    endYear: 2018,
    category: "Figuras",
    tags: ["adventure-time", "finn", "jake", "2018"],
    sortOrder: 42,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Cartoon Network",
    slug: "cartoon-network-2019",
    description: "Promoción especial con diversos personajes del universo Cartoon Network unidos.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Cartoon network chocolate_1755196507571_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/Cartoon network chocolate_1755196507571_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2019,
    endYear: 2019,
    category: "Figuras",
    tags: ["cartoon-network", "crossover", "personajes"],
    sortOrder: 43,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Corazones Vualá",
    slug: "corazones-vuala-2019",
    description: "Promoción romántica de Vualá con mini colgantes en forma de corazón.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2019,
    endYear: 2019,
    category: "Mini colgantes",
    tags: ["corazones", "amor", "romantico"],
    sortOrder: 44,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Teen Titans GO",
    slug: "teen-titans-go-2020",
    description: "Promoción de Teen Titans GO con Robin, Raven, Beast Boy, Starfire y Cyborg.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Teen titans vainilla version 1_1755219753444_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/Teen titans vainilla version 1_1755219753444_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2020,
    endYear: 2020,
    category: "Figuras",
    tags: ["teen-titans", "go", "heroes"],
    sortOrder: 45,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Steven Universe",
    slug: "steven-universe-2020",
    description: "Promoción de Steven Universe con gemas mágicas y aventuras intergalácticas.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2020,
    endYear: 2020,
    category: "Figuras",
    tags: ["steven-universe", "gemas", "cartoon-network"],
    sortOrder: 46,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "FUNKY TUBERS",
    slug: "funky-tubers-2021",
    description: "Promoción moderna de FUNKY TUBERS con mini colgantes de YouTubers y streamers.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/Pinki pow punks funki tubers vainilla 2020_1755219753444_rotated.png",
    wrapperPhotosUrls: ["/attached_assets/rotated/Pinki pow punks funki tubers vainilla 2020_1755219753444_rotated.png"],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2021,
    endYear: 2021,
    category: "Mini colgantes",
    tags: ["youtube", "streamers", "digital"],
    sortOrder: 47,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Among Us",
    slug: "among-us-2021",
    description: "Promoción del popular videojuego Among Us con crewmates y impostores.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2021,
    endYear: 2021,
    category: "Figuras",
    tags: ["among-us", "videojuegos", "impostor"],
    sortOrder: 48,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Villanous",
    slug: "villanous-2022",
    description: "Promoción de Villanos con los malvados más icónicos de Cartoon Network.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2022,
    endYear: 2022,
    category: "Figuras",
    tags: ["villanos", "cartoon-network", "malvados"],
    sortOrder: 49,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Plantas vs Zombies",
    slug: "plantas-vs-zombies-2022",
    description: "Promoción del popular videojuego tower defense con plantas defendiendo contra zombies.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2022,
    endYear: 2022,
    category: "Figuras",
    tags: ["plantas-vs-zombies", "videojuegos", "tower-defense"],
    sortOrder: 50,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "XOXO MASCOTAS",
    slug: "xoxo-mascotas-2022",
    description: "Promoción de mascotas adorables con figuras de perros, gatos y otros animales domésticos.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2022,
    endYear: 2022,
    category: "Figuras",
    tags: ["mascotas", "animales", "xoxo"],
    sortOrder: 51,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Angry Birds 2023",
    slug: "angry-birds-2023",
    description: "Nueva edición 2023 de Angry Birds con los pájaros enojados en aventuras actualizadas.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2023,
    endYear: 2023,
    category: "Figuras",
    tags: ["angry-birds", "2023", "actualizados"],
    sortOrder: 52,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Pinky Pow Punks",
    slug: "pinky-pow-punks-2023",
    description: "Promoción moderna con mini colgantes de personajes punk coloridos y rebeldes.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2023,
    endYear: 2023,
    category: "Mini colgantes",
    tags: ["pinky", "punk", "rebeldes"],
    sortOrder: 53,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Pokémon",
    slug: "pokemon-2023",
    description: "Promoción de Pokémon con figuras de Pikachu y otros pokémon populares.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2023,
    endYear: 2023,
    category: "Figuras",
    tags: ["pokemon", "pikachu", "nintendo"],
    sortOrder: 54,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "FNAF",
    slug: "fnaf-2024",
    description: "Promoción de Five Nights at Freddy's con figuras de los animatrónicos del popular videojuego de terror.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2024,
    endYear: 2024,
    category: "Figuras",
    tags: ["fnaf", "five-nights", "horror"],
    sortOrder: 55,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Bob Esponja 2024",
    slug: "bob-esponja-2024",
    description: "Edición especial del 25° aniversario de Bob Esponja con figuras conmemorativas.",
    imageUrl: null,
    wrapperPhotoUrl: "/attached_assets/rotated/bob esponja 2024 cajeta frontal_1755196507569_rotated.png",
    wrapperPhotosUrls: [
      "/attached_assets/rotated/bob esponja 2024 cajeta frontal_1755196507569_rotated.png",
      "/attached_assets/rotated/Bob esponja 2024 piña frontal_1755196507569_rotated.png",
      "/attached_assets/rotated/Vainilla bob esponja 2024_1755219753445_rotated.png"
    ],
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: null,
    startYear: 2024,
    endYear: 2024,
    category: "Figuras",
    tags: ["bob-esponja", "25-aniversario", "conmemorativo"],
    sortOrder: 56,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Grupo Chespirito",
    slug: "grupo-chespirito-2025",
    description: "Colección especial celebrando el legado de Roberto Gómez Bolaños con personajes del Chavo, Chapulín Colorado y otros clásicos del humor mexicano.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: "https://www.youtube.com/watch?v=qsq1w3eZX2E",
    startYear: 2025,
    endYear: 2025,
    category: "Figuras",
    tags: ["chespirito", "chavo", "chapulin"],
    sortOrder: 57,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });

  await createPromotion({
    brandId: brands.vuala.id,
    name: "Multiversus",
    slug: "multiversus-2025",
    description: "Épica colección del crossover Multiversus incluyendo héroes de DC, personajes de Cartoon Network y Warner Bros en batallas interdimensionales.",
    imageUrl: null,
    wrapperPhotoUrl: null,
    wrapperPhotosUrls: null,
    wrapperRotation: 0,
    promotionImagesUrls: null,
    youtubeCommercialUrl: null,
    buffetGamesVideoUrl: "https://www.youtube.com/watch?v=qsq1w3eZX2E",
    startYear: 2025,
    endYear: 2025,
    category: "Figuras",
    tags: ["multiversus", "dc", "crossover"],
    sortOrder: 58,
    wrapperScale: 100,
    wrapperOffsetX: 0,
    wrapperOffsetY: 0,
  });
};